# Site settings
author: Amanda Rolon
title: Why I decided to learn Software Engineering
header-img: img/home-bg.png
email: abrolon87@gmail.com
copyright_name: Amanda Rolon
description: > # this means to ignore newlines until "baseurl:"
  The Beginning
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  abrolon87

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
